# Generated by Django 3.1.4 on 2021-01-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_author_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
