# Generated by Django 3.1.4 on 2021-01-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210130_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date_of_birth', models.CharField(max_length=200, verbose_name='date of birth')),
                ('born_location', models.CharField(max_length=200, verbose_name='born location')),
                ('about', models.CharField(max_length=5000, verbose_name='about')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200, verbose_name='quote')),
                ('tags', models.CharField(max_length=200, verbose_name='tags')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.author')),
            ],
        ),
    ]
